name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - '*'
  pull_request:
    branches:
      - main
      - '*'

jobs:
  # CI: Lint, Prettier, Build
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Frontend Setup
        uses: ./.github/workflows/shared/frontend-setup

      - name: Lint check
        run: pnpm run lint-check

      - name: Prettier check
        run: pnpm run prettier-check

      - name: Build
        run: pnpm run build

  # CD: Deploy to EC2
  cd:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Frontend Setup
        uses: ./.github/workflows/shared/frontend-setup

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # Write SSH key to a file
          echo "$EC2_KEY" > ec2_key.pem
          chmod 600 ec2_key.pem

          # SSH into EC2 and deploy
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd graphite
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart graphite || pm2 start "pnpm start" --name graphite
          EOF

      - name: Output Deployment Confirmation
        run: |
          echo "Deployed to EC2 at ${{ secrets.EC2_HOST }}"
